### ISSUE TITLE
Error in Kamelet example

### ISSUE THREAD

**Issue by nicolaferraro** [citrusframework/yaks#165]
I've done some other tests, but I see that also the example fails:

```
cd examples/kamelets
yaks test kamelet-resource.feature --resource timer-to-log.groovy --resource timer-source.kamelet.yaml
```

Output:

```
+ test-kamelet-resource-buba4je8lhbb5hkgshkg › test



test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	| 
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	| ------------------------------------------------------------------------
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	|        .__  __                       
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	|   ____ |__|/  |________ __ __  ______
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	| _/ ___\|  \   __\_  __ \  |  \/  ___/
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	| \  \___|  ||  |  |  | \/  |  /\___ \ 
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	|  \___  >__||__|  |__|  |____//____  >
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	|      \/                           \/
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	| 
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	| C I T R U S  T E S T S  3.0.0-M1
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	| 
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	| ------------------------------------------------------------------------
test-kamelet-resource-buba4je8lhbb5hkgshkg test INFO	| 
test-kamelet-resource-buba4je8lhbb5hkgshkg test 
test-kamelet-resource-buba4je8lhbb5hkgshkg test Scenario: Create Kamelet from file                # org/citrusframework/yaks/kamelet-resource.feature:9
test-kamelet-resource-buba4je8lhbb5hkgshkg test   Given Disable auto removal of Kamelet resources # org.citrusframework.yaks.camelk.KameletSteps.disableAutoRemove()
test-kamelet-resource-buba4je8lhbb5hkgshkg test   Given Camel-K resource polling configuration    # org.citrusframework.yaks.camelk.CamelKSteps.configureResourcePolling(java.util.Map<java.lang.String, java.lang.Object>)
test-kamelet-resource-buba4je8lhbb5hkgshkg test   Given load Kamelet timer-source.kamelet.yaml    # org.citrusframework.yaks.camelk.KameletSteps.loadKameletFromFile(java.lang.String)
test-kamelet-resource-buba4je8lhbb5hkgshkg test       com.consol.citrus.exceptions.TestCaseFailedException: An error has occurred.
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.consol.citrus.DefaultTestCase.executeAction(DefaultTestCase.java:197)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.consol.citrus.DefaultTestCaseRunner.run(DefaultTestCaseRunner.java:118)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.citrusframework.yaks.camelk.KameletSteps.loadKameletFromFile(KameletSteps.java:183)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at ?.load Kamelet timer-source.kamelet.yaml(classpath:org/citrusframework/yaks/kamelet-resource.feature:10)
test-kamelet-resource-buba4je8lhbb5hkgshkg test Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:248)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:199)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:495)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:451)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:416)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:397)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:890)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:233)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:187)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:79)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:412)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:79)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:410)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:79)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.citrusframework.yaks.camelk.actions.kamelet.CreateKameletAction.createKamelet(CreateKameletAction.java:124)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.citrusframework.yaks.camelk.actions.kamelet.CreateKameletAction.doExecute(CreateKameletAction.java:76)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:55)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.consol.citrus.DefaultTestCase.executeAction(DefaultTestCase.java:190)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.consol.citrus.DefaultTestCaseRunner.run(DefaultTestCaseRunner.java:118)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.citrusframework.yaks.camelk.KameletSteps.loadKameletFromFile(KameletSteps.java:183)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at java.lang.reflect.Method.invoke(Method.java:498)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.java.Invoker.invoke(Invoker.java:27)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:27)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:46)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.core.runner.TestCase.run(TestCase.java:51)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:185)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:83)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:219)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
test-kamelet-resource-buba4je8lhbb5hkgshkg test Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'string' as a subtype of `com.fasterxml.jackson.module.jsonSchema.types.ObjectSchema`: Class `com.fasterxml.jackson.module.jsonSchema.types.StringSchema` not subtype of `com.fasterxml.jackson.module.jsonSchema.types.ObjectSchema`
test-kamelet-resource-buba4je8lhbb5hkgshkg test  at [Source: (BufferedInputStream); line: 1, column: 1924] (through reference chain: org.citrusframework.yaks.camelk.model.Kamelet["spec"]->org.citrusframework.yaks.camelk.model.KameletSpec["types"]->java.util.LinkedHashMap["out"]->org.citrusframework.yaks.camelk.model.KameletSpec$TypeSpec["schema"])
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1784)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:194)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:115)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:99)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1209)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:540)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:377)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3511)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:246)
test-kamelet-resource-buba4je8lhbb5hkgshkg test 	... 59 more
```

It would be nice if examples were also tested in CI.

**Comment by christophd** [comment]
Got this reproduced now. This happens when the Camel-K integration is already up and running (maybe from another test run). In this case the YAKS operation will replace the integration and this hits the error
