### ISSUE TITLE
Testing Camel-K integrations which use simple() expressions does not work.

### ISSUE THREAD

**Issue by Emmeral** [citrusframework/yaks#292]
I tried running the following test which is an alteration of the [example test given in the documentation](https://citrusframework.org/yaks/reference/html/index.html#steps-camel-k):
```
Feature: Prints Bar
  Scenario: Starts
    Given create Camel-K integration reproducer.groovy
      """
      from('timer:tick?period=1000')
        .setBody().constant('{"foo":"bar"}')
        .unmarshal().json()
        .transform(simple('${body[foo]}'))
        .log('${body}');
      """
    Given Camel-K integration reproducer is running
    Then Camel-K integration reproducer should print bar

```

I expected it to finish successful. Instead I got the following exception:

```
com.consol.citrus.exceptions.TestCaseFailedException: Unknown variable 'body[foo]'
 at com.consol.citrus.DefaultTestCase.executeAction(DefaultTestCase.java:144)
 at com.consol.citrus.DefaultTestCaseRunner.run(DefaultTestCaseRunner.java:125)
 at org.citrusframework.yaks.camelk.CamelKSteps.createNewIntegration(CamelKSteps.java:124)
 at *.create Camel-K integration reproducer.groovy(classpath:org/citrusframework/yaks/repoducer.feature:3)
Caused by: com.consol.citrus.exceptions.CitrusRuntimeException: Unknown variable 'body[foo]'
 at com.consol.citrus.context.TestContext.getVariableObject(TestContext.java:229)
 at com.consol.citrus.context.TestContext.getVariable(TestContext.java:204)
 at com.consol.citrus.context.TestContext.getVariable(TestContext.java:192)
 at com.consol.citrus.variable.VariableUtils.replaceVariablesInString(VariableUtils.java:177)
 at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:431)
 at com.consol.citrus.context.TestContext.replaceDynamicContentInString(TestContext.java:416)
 at org.citrusframework.yaks.camelk.actions.integration.CreateIntegrationAction.createIntegration(CreateIntegrationAction.java:78)
 at org.citrusframework.yaks.camelk.actions.integration.CreateIntegrationAction.doExecute(CreateIntegrationAction.java:72)
 at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:58)
 at com.consol.citrus.DefaultTestCase.executeAction(DefaultTestCase.java:137)
 at com.consol.citrus.DefaultTestCaseRunner.run(DefaultTestCaseRunner.java:125)
 at org.citrusframework.yaks.camelk.CamelKSteps.createNewIntegration(CamelKSteps.java:124)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
 at io.cucumber.java.Invoker.invoke(Invoker.java:24)
 at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
 at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
 at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
 at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
 at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
 at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
 at io.cucumber.core.runner.TestStep.run(TestStep.java:64)
 at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
 at io.cucumber.core.runner.TestCase.run(TestCase.java:104)
 at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
 at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:151)
 at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:135)
 at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:27)
 at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 at io.cucumber.junit.Cucumber.runChild(Cucumber.java:199)
 at io.cucumber.junit.Cucumber.runChild(Cucumber.java:90)
 at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
 at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
 at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
 at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
 at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
 at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:234)
 at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
 at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
 at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
 at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
 at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
 at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
 at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
 at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
 at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
 at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

It seems like YAKS tries to replace variables in the Camel-K integration. I could not find any notes regarding this behavior in the documentation.

**Comment by christophd** [comment]
Hi,

this is because the Camel simple expression syntax collides with the Citrus test variable syntax. Both use `${expression}` and Citrus can not find the variable of name `body` in your case.

Two solutions that I have in mind:
1) escape the simple expression so Citrus will not try to resolve the test variable: `${//body[foo]//}`
2) escape the expression the Camel way: `$simple{body[foo]}`

Let me know if this works for you.

**Comment by Emmeral** [comment]
Thanks for the quick reply. The second solution worked. 

However, the variable replacement is also applied if the integration is loaded from an external file. Is this expected behavior?

**Comment by christophd** [comment]
yes the test variables should be replaced regardless of the integration source (inline or external file). this is for instance to replace variables that have been bound as secrets to the test pod
