### ISSUE TITLE
Runtime Error when running "yaks install" 

### ISSUE THREAD

**Issue by ichtestemalwieder** [citrusframework/yaks#489]
Hello experts, 

I currently get the following error when running yaks install on OpenShift

```
[root@ocp-svc ~]# ./yaks install
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x18cbe7a]

goroutine 1 [running]:
github.com/citrusframework/yaks/pkg/util/olm.maybeSetEnvVars(0xc000788540, {0xc000759e70?, 0x1f78056?, 0x4?})
        github.com/citrusframework/yaks/pkg/util/olm/operator.go:214 +0x5a
github.com/citrusframework/yaks/pkg/util/olm.Install({0x22a7078, 0xc0005723c0}, {0x22ca3f8?, 0xc0007ace70?}, {0xc0005b9224?, 0x4}, 0x1, {{0x1f844b3, 0xd}, {0x1f78056, ...}, ...}, ...)
        github.com/citrusframework/yaks/pkg/util/olm/operator.go:170 +0x458
github.com/citrusframework/yaks/pkg/cmd.(*installCmdOptions).install(0xc0002fa0f0, 0x0?, {0x0?, 0x0?, 0x0?})
        github.com/citrusframework/yaks/pkg/cmd/install.go:140 +0x4c5
github.com/citrusframework/yaks/pkg/cmd.newCmdInstall.func1(0xc0002bdb00?, {0x33225e0?, 0x4?, 0x1f78132?})
        github.com/citrusframework/yaks/pkg/cmd/install.go:48 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc00056c900, {0x33225e0, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000386900)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x22a7078?)
        github.com/spf13/cobra@v1.7.0/command.go:992 +0x13
main.main()
        ./main.go:38 +0x65
```

```
[root@ocp-svc ~]# ./yaks version
YAKS 0.17.1
```

```
[root@ocp-svc ~]# oc version
Client Version: 4.14.0-202310201027.p0.g0c63f9d.assembly.stream-0c63f9d
Kustomize Version: v5.0.1
Server Version: 4.14.1
Kubernetes Version: v1.27.6+f67aeb3
```

Same Issuse on windows... Does anyone have a tip for me, how to debug this further? 
Thanks very much for any help!

**Comment by christophd** [comment]
Looks like this is a bug and the OLM based install is broken. I will have a look how to fix.

You could fallback to non-olm based installation with `yaks install --olm=false` or you could install on OpenShift via OperatorHub and use the OpenShift UI for this.

Many thanks for finding this issue!
